# Generated by Django 4.2.5 on 2023-10-09 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_remove_shop_trainer'),
        ('Trainer', '0003_trainer_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='shop',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shop.shop'),
        ),
    ]
