# Generated by Django 4.2.5 on 2023-10-09 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_remove_shop_items_shop_items'),
        ('Items', '0001_initial'),
        ('Trainer', '0007_alter_trainer_items_alter_trainer_pokemon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='items',
            field=models.ManyToManyField(default=None, related_name='trainers', to='Items.item'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='shop',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Shop.shop'),
        ),
    ]
