# Generated by Django 4.2.5 on 2023-10-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0001_initial'),
        ('Trainer', '0009_alter_trainer_items_alter_trainer_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='items',
            field=models.ManyToManyField(blank=True, default=None, related_name='trainers', to='Items.item'),
        ),
    ]
