# Generated by Django 4.2.5 on 2023-10-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_pokemon_max_health_alter_pokemon_health'),
        ('Items', '0005_alter_item_unique_together'),
        ('Trainer', '0010_alter_trainer_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='items',
            field=models.ManyToManyField(blank=True, default=None, related_name='trainers_items', to='Items.item'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='pokemon',
            field=models.ManyToManyField(blank=True, default=None, related_name='trainer_pokemon', to='pokemon.pokemon'),
        ),
    ]
