version: "3"
services:
  apollo-server:
    build: ./apolloserver
  api:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
    depends_on:
      - db
  nginx:
    build: 
      context: .
      dockerfile: ./local-webserver/Dockerfile
    restart: always
    ports:
      - "80:80"
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD

volumes:
  postgres_data: