#########################################
# The "production" compose file builds 
# on your EC2 instance
#########################################

version: "3"
services:
  apollo-server:
    image: $DOCKERHUB_UNAME/pokemonko-apollo_api-prod:$NEW_VERSION
  api:
    image: $DOCKERHUB_UNAME/pokemonko_api-prod:$NEW_VERSION 
    environment:
      - PRODUCTION=$PRODUCTION
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
    depends_on:
      - db
  nginx:
    image: $DOCKERHUB_UNAME/pokemonko_webserver-prod:$NEW_VERSION
    restart: always
    ports:
      - "443:443"
      - "80:80"
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD

volumes:
  postgres_data: