# Generated by Django 4.2.5 on 2023-10-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0010_alter_pokemon_defense_alter_pokemon_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='defense',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='health',
            field=models.IntegerField(default=350),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='max_health',
            field=models.IntegerField(default=350),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='power',
            field=models.IntegerField(default=75),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='totalXP',
            field=models.IntegerField(default=125),
        ),
    ]
