# Generated by Django 4.2.5 on 2023-10-09 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Items', '0001_initial'),
        ('Trainer', '0002_trainer_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_items', to='Items.item')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='Trainer.trainer')),
            ],
        ),
    ]
