# Generated by Django 4.2.5 on 2023-10-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0002_item_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_class',
            field=models.CharField(default='health', max_length=10),
        ),
    ]
