# Generated by Django 4.2.5 on 2023-10-10 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0004_alter_item_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set(),
        ),
    ]
