# Generated by Django 4.2.5 on 2023-10-10 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0003_item_item_class'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('name', 'value', 'stat_boost', 'item_class')},
        ),
    ]
