# Generated by Django 4.2.5 on 2023-10-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0005_alter_item_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(default='normal', max_length=15),
        ),
    ]
