# Generated by Django 4.2.5 on 2023-10-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='type',
            field=models.CharField(default='Normal', max_length=15),
        ),
    ]
