# Generated by Django 4.2.5 on 2023-10-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0001_initial'),
        ('Trainer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='items', to='Items.item'),
        ),
    ]
