# Generated by Django 4.2.5 on 2023-10-09 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_remove_shop_trainer'),
        ('Trainer', '0002_trainer_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='shop',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Shop.shop'),
        ),
    ]
