# Generated by Django 4.2.5 on 2023-10-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0007_pokemon_defense'),
        ('Trainer', '0014_alter_trainer_enemy_pokemon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='enemy_pokemon',
            field=models.ManyToManyField(blank=True, default=None, related_name='enemy_pokemon', to='pokemon.pokemon'),
        ),
    ]
