# Generated by Django 4.2.5 on 2023-10-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_pokemon_max_health_alter_pokemon_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='power',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='health',
            field=models.IntegerField(default=75),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='max_health',
            field=models.IntegerField(default=75),
        ),
    ]
