# Generated by Django 4.2.5 on 2023-10-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_pokemon_power_alter_pokemon_health_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='totalXP',
            field=models.IntegerField(default=60),
        ),
    ]
