# Generated by Django 4.2.5 on 2023-10-13 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0005_pokemon_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='type',
            new_name='types',
        ),
    ]
