# Generated by Django 4.2.5 on 2023-10-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0006_rename_type_pokemon_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='defense',
            field=models.IntegerField(default=10),
        ),
    ]
