# Generated by Django 4.2.5 on 2023-10-22 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0007_pokemon_defense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='health',
            field=models.IntegerField(default=750),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='max_health',
            field=models.IntegerField(default=750),
        ),
    ]
