# Generated by Django 4.2.5 on 2023-10-23 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0008_alter_pokemon_health_alter_pokemon_max_health'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='health',
            field=models.IntegerField(default=450),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='max_health',
            field=models.IntegerField(default=450),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='totalXP',
            field=models.IntegerField(default=155),
        ),
    ]
