# Generated by Django 4.2.5 on 2023-10-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0009_alter_pokemon_health_alter_pokemon_max_health_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='defense',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='power',
            field=models.IntegerField(default=45),
        ),
    ]
