# Generated by Django 4.2.5 on 2023-10-09 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='trainer',
        ),
    ]
