# Generated by Django 4.2.5 on 2023-10-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0001_initial'),
        ('Shop', '0002_remove_shop_trainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='items',
        ),
        migrations.AddField(
            model_name='shop',
            name='items',
            field=models.ManyToManyField(related_name='shop_items', to='Items.item'),
        ),
    ]
